"""
Discrepancy Analyzer - Edge-dependency consistency analysis.

Deterministically compares every ``task_link`` in a target DAG with DAGs
generated by multiple models. An edge passes when all models agree and warns
when any model disagrees. Edges generated by models but absent from the target
DAG are also marked as warnings.
"""

from typing import Dict, List, Any, Tuple
from dataclasses import dataclass


@dataclass
class DiscrepancyReport:
    """Discrepancy report retained for backward compatibility."""
    task_id: str
    task_links: List[Dict[str, Any]]
    summary: Dict[str, Any]


class DiscrepancyAnalyzer:
    """
    Edge-dependency consistency analyzer.

    Counts how many of N model-generated DAGs contain each target ``task_link``
    and classifies the edge from that agreement count.
    """

    def __init__(self, llm_client=None, enable_llm_analysis: bool = True):
        """
        Args:
            llm_client: Retained for compatibility; deterministic comparison
                does not use an LLM.
            enable_llm_analysis: Retained for compatibility.
        """
        self.llm_client = llm_client
        self.enable_llm_analysis = enable_llm_analysis

    @staticmethod
    def _normalize_link(source: str, target: str) -> Tuple[str, str]:
        """Normalize an edge by trimming surrounding whitespace."""
        return (str(source).strip(), str(target).strip())

    @staticmethod
    def _extract_link_set(dag: Dict) -> set:
        """Extract the edge set from one DAG."""
        link_set = set()
        for link in dag.get("task_links", []):
            if isinstance(link, dict):
                s = link.get("source", "")
                t = link.get("target", "")
                if s and t:
                    link_set.add(
                        DiscrepancyAnalyzer._normalize_link(s, t)
                    )
        return link_set

    def analyze_task(
        self,
        task: Dict,
        model_results: List,
    ) -> Dict[str, Any]:
        """
        Analyze agreement for every target edge across model-generated DAGs.

        Rules:
        - Every model includes the edge -> pass.
        - Any model omits the edge -> warn.
        - A model adds an edge absent from the target -> warn.

        Args:
            task: Target task containing ``task_links`` to evaluate.
            model_results: Simulation results containing generated DAGs.

        Returns:
            {
                "task_links": [
                    {
                        "source": "...",
                        "target": "...",
                        "status": "pass" | "warn"
                    },
                    ...
                ]
            }
        """
        target_links = task.get("task_links", [])

        # Collect edge sets from successful generations.
        dag_link_sets = []
        for result in model_results:
            dag = getattr(result, "generated_dag", None)
            if dag and not getattr(result, "error", None):
                link_set = self._extract_link_set(dag)
                dag_link_sets.append(link_set)

        n_dags = len(dag_link_sets)
        print(f"📊 Discrepancy Analysis: {n_dags} valid DAGs for comparison")

        # Keep target edges separately to detect model-added edges.
        original_links = set()
        for link in target_links:
            source = str(link.get("source", "")).strip()
            target = str(link.get("target", "")).strip()
            if source and target:
                original_links.add(self._normalize_link(source, target))

        if n_dags == 0:
            return {
                "task_links": [
                    {
                        "source": link.get("source", ""),
                        "target": link.get("target", ""),
                        "status": "warn",
                        "model_status": "warn",
                        "model_match_count": 0,
                        "model_count": 0,
                    }
                    for link in target_links
                ],
                "summary": {
                    "model_count": 0,
                    "pass_count": 0,
                    "warn_count": len(target_links),
                },
            }

        # Compare every target edge.
        result_links = []
        for link in target_links:
            source = link.get("source", "")
            target = link.get("target", "")
            normalized = self._normalize_link(source, target)

            # Count model DAGs containing this edge.
            match_count = sum(
                1 for link_set in dag_link_sets if normalized in link_set
            )

            # Pass only on unanimous agreement.
            status = "pass" if match_count == n_dags else "warn"

            result_links.append(
                {
                    "source": source,
                    "target": target,
                    "status": status,
                    "model_status": status,
                    "model_match_count": match_count,
                    "model_count": n_dags,
                }
            )

        # Add model-generated edges absent from the target as warnings.
        all_model_edges = set()
        for link_set in dag_link_sets:
            all_model_edges |= link_set

        extra_edges = all_model_edges - original_links
        for source, target in sorted(extra_edges):
            match_count = sum(
                1 for link_set in dag_link_sets if (source, target) in link_set
            )
            result_links.append(
                {
                    "source": source,
                    "target": target,
                    "status": "warn",
                    "model_status": "warn",
                    "model_match_count": match_count,
                    "model_count": n_dags,
                }
            )

        # Print a summary.
        pass_count = sum(1 for r in result_links if r["status"] == "pass")
        warn_count = sum(1 for r in result_links if r["status"] == "warn")
        print(
            f"   ✅ pass: {pass_count}  ⚠️ warn: {warn_count}  "
            f"(extra edges from models: {len(extra_edges)})"
        )

        return {
            "task_links": result_links,
            "summary": {
                "model_count": n_dags,
                "pass_count": pass_count,
                "warn_count": warn_count,
                "extra_edge_count": len(extra_edges),
            },
        }
